Aggiunta pagina l10n
MozillaItalia/mozillaitalia.github.io pull request #69
Opened 2020-11-30 20:30 UTC by xplosionmind

Creata pagina dedicata alla localizzazione in Mozilla Italia, come da #24.

2020-11-30 22:52 UTC, Sav22999 commented
![image](https://user-images.githubusercontent.com/32335378/100675361-1a404600-3367-11eb-8f2f-dcc19fe4f979.png)

2020-11-30 22:53 UTC, Sav22999 commented
Avevamo detto di non utilizzare Jekyll o altro, dal momento che il sito è statico e non ha bisogno di gestione varia continua.

2020-11-30 23:05 UTC, Sav22999 requested changes
Rimuovere Jekyll

2020-11-30 23:37 UTC, xplosionmind commented
Ok mi ero perso la discussione su Jekyll, anche se avevo fatto la PR prima di implementarlo… si vede che se aggiorno la mia repo, in automatico si aggiorna la pull request.

2020-11-30 23:38 UTC, Sav22999 commented
Sì, se apri una PR, in automatico (se lavori sullo stesso branch) appena crei dei commit li inserisce nella stessa PR

2020-11-30 23:49 UTC, xplosionmind commented
Rimosso Jekyll. Tutto come prima, aggiunta solo pagine 404 e l10n.

2020-12-01 00:59 UTC, Sav22999 approved these changes

2020-12-01 01:10 UTC, Sav22999 commented
Ho modificato la pagina 404 con questa:

![image](https://user-images.githubusercontent.com/32335378/100684271-4913e780-337a-11eb-971c-100b4ec8bafd.png)


E modificato pochissimo la pagina l10n:

![image](https://user-images.githubusercontent.com/32335378/100684341-6e085a80-337a-11eb-9519-1b2ada0025df.png)

Fammi sapere cosa ne pensi. Se sei d'accordo approvo la PR

2020-12-01 08:00 UTC, xplosionmind commented
Con i numeri grossi e con i loghini è molto più bella. Sono d'accordo!

Grazie @Sav22999

2020-12-01 08:54 UTC, merged